name: Deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron: '12 12 * * *'
  workflow_dispatch:
    inputs:
      input_name:
         

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "There is nothing to deploy here"
        echo "Input value: ${{ github.event.inputs.sure }}"
