name: Deployment

on:
  push:
    branches:
      - $default_branch
    tags:
      - "20.*"
  workflow_dispatch:
    inputs:
      sure:
        description: Are you sure?
        required: true
        default: 'no'
    

jobs:

  Build:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: notlmn/daily-version-action@use-actions-core
      name: Create tag if necessary
      id: daily-version

  Store:
    needs: Build
    if: github.event_name == 'push' || needs.Build.outputs.created
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version created ${{ needs.Build.outputs.version }}"
